apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: {{ .Values.clusterSize }}
  version: "1.1.0"
  auth:
    clientsAuthSecret: "nats-clients-auth"
    clientsAuthTimeout: 5
