{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nats-clients-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "nats.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    test: "{{ .Values.auth.password }}"
type: Opaque
data:
  clients-auth.json: {{ .Files.Get "client-auth.json" | b64enc}}
{{- end }}
